title: Ctrl Alt MD
author: Jake McClure, M.D.
email: holler@JakeMcClure.net
description: Rebooting healthcare for the digital age
baseurl:
url: "https://JakeMcClure.github.io/" # the base hostname & protocol for your site
twitter_username: Jake_McClure
github_username:  JakeMcClure
id_f: 750992151742709
id_g: UA-76343771-1

# Build settings
#plugins:
# - jekyll-coffeescript
#sass:
#  sass_dir: _sass
collections:
  lab:
    output: true
    permalink: /:collection/:name/
  tools:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      author: "Jake McClure, M.D."
      excerpt_separator: "<!--excerpt-->"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "_lab"
    values:
      layout: "page"
  -
    scope:
      path: "_tools"
    values:
      layout: "page"
timezone: America/New_York
theme_color: 3151a7
markdown: kramdown
permalink: /:year/:title/
exclude: [
  "node_modules",
  "LICENSE",
  "package.json",
  "README.md",
  "Gemfile",
  "gulpfile.babel.js",
  ".babelrc",
  ".gitignore",
  "sass",
  "_sass",
  "scss",
  "validate",
  "sandbox",
  "google*.html"
]
